### PR TITLE
Add multiselect

### PR DESCRIPTION
**Pull request by DTCurrie**
Screenshot 2023-08-30 at 1 16 53 PM

### CODE REVIEW

**Comment by micheal-parks** [comment]
I'd recommend moving the dropdown to above / covering the pills. Had a few discussions with design during building the original multiselect about whether or not to do this and we agreed that having both the pills and the dropdown visible was a worse UX because we're showing two element sections at once that have redundant functionality (you can remove a pill both in the dropdown and by clicking x)

**Comment by DTCurrie** [comment]
> I'd recommend moving the dropdown to above / covering the pills. Had a few discussions with design during building the original multiselect about whether or not to do this and we agreed that having both the pills and the dropdown visible was a worse UX because we're showing two element sections at once that have redundant functionality (you can remove a pill both in the dropdown and by clicking x)

Ah ok, I was going off the old designs since new ones haven't been provided for multiselects yet. Kind of hesitant to stray too far from those until we have proper figmas, but I can update this assuming there isn't any other big design changes expected.

**Comment by DTCurrie** [comment]
> > I'd recommend moving the dropdown to above / covering the pills. Had a few discussions with design during building the original multiselect about whether or not to do this and we agreed that having both the pills and the dropdown visible was a worse UX because we're showing two element sections at once that have redundant functionality (you can remove a pill both in the dropdown and by clicking x)
> 
> Ah ok, I was going off the old layout since new ones haven't been provided for multiselects yet. Kind of hesitant to stray too far from those until we have proper figmas, but I can update this assuming there isn't any other big design changes expected.
> 
> We stopped using the dropdown, so that may be why it is different.

Updated:

Screenshot 2023-08-30 at 1 51 12 PM

**Review by ethanlook — APPROVED** [review]
Looks great! Nice code sharing.

Don't forget to bump the version!

**Review by ethanlook — APPROVED** [review]

**Pull request merged**
