### PR TITLE
Make preventHandler use reactive

### PR DESCRIPTION
**Pull request by ethanlook**
The handlers that used `preventDefault` would be stuck in their original state because the use of `preventHandler` wasn't reactive.

### CODE REVIEW

**Review by DTCurrie — APPROVED** [review]
✅

**Comment by DTCurrie** [comment]
Sorry just merged a PR that also bumped to the same version.

**Review by mcous — APPROVED** [review]
Good catch. I think this issue probably affects other functions in the codebase; I'm definitely guilty of writing a non-reactive handler for click-outside logic before we had the action-based approach

**Comment by DTCurrie** [comment]
> Good catch. I think this issue probably affects other functions in the codebase; I'm definitely guilty of writing a non-reactive handler for click-outside logic before we had the action-based approach

Yeah I will keep an eye out for these as I go through the RC but we may want to make a pass of all the current stuff.

**Comment by ethanlook** [comment]
> Sorry just merged a PR that also bumped to the same version.

No worries!

**Pull request merged**
